name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Install test dependencies
      run: sudo env DEBIAN_FRONTEND=noninteractive apt-get -qq -y install pbzip2
    - name: Run tests
      run: |
        cd test
        run_tests() {
          rc=0
          for f in * ; do
            [ -f "$f" ] && [ -x "$f" ] && { 
              echo "$f" ; ./"$f" || { rc=1 ; break ; }
            }
          done
          return $rc
        }
        run_tests
