name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Run tests
      run: |
        cd test
        # using GNU find
        find . -maxdepth 1 -executable -type f -print \( -exec {} \; -o -quit \)
